In [19]:
stuff = """
Private Third Class 	2000 	10,000 	
Private Second Class 	3000 	15,000 	
Private First Class 	4000 	20,000 	
Corporal 	5000 	25,000 	
Sergeant Third Class 	6000 	30,000 	Must complete Company Hunting Log Rank 1
Sergeant Second Class 	7000 	35,000 	Unlocks Expert Delivery
Sergeant First Class 	8000 	40,000 	
Chief Sergeant 	9000 	45,000 	Must complete Shadows Uncast
Second Lieutenant 	10,000 	50,000 	Must complete Gilding the Bilious
First Lieutenant 	0 	80,000 	Adventurer Squadrons Rank 3 by completing Flagged Mission: Crystal Recovery
Captain """

In [21]:
[z[:-1] for z in [x.split("\t")[0] for x in stuff.split("\n")][1:]]

['Private Third Class',
 'Private Second Class',
 'Private First Class',
 'Corporal',
 'Sergeant Third Class',
 'Sergeant Second Class',
 'Sergeant First Class',
 'Chief Sergeant',
 'Second Lieutenant',
 'First Lieutenant',
 'Captain']

In [23]:
import pandas as pd

In [33]:
df = pd.read_csv("Item.csv",skiprows=[0,2])

In [34]:
df.columns

Index(['#', 'Singular', 'Adjective', 'Plural', 'PossessivePronoun',
       'StartsWithVowel', 'Unnamed: 6', 'Pronoun', 'Article', 'Description',
       'Name', 'Icon', 'Level{Item}', 'Rarity', 'FilterGroup',
       'AdditionalData', 'ItemUICategory', 'ItemSearchCategory',
       'EquipSlotCategory', 'ItemSortCategory', 'Unnamed: 20', 'StackSize',
       'IsUnique', 'IsUntradable', 'IsIndisposable', 'Lot', 'Price{Mid}',
       'Price{Low}', 'CanBeHq', 'DyeCount', 'IsCrestWorthy', 'ItemAction',
       'CastTime<s>', 'Cooldown<s>', 'ClassJob{Repair}', 'Item{Repair}',
       'Item{Glamour}', 'Desynth', 'IsCollectable', 'AlwaysCollectable',
       'AetherialReduce', 'Level{Equip}', 'RequiredPvpRank',
       'EquipRestriction', 'ClassJobCategory', 'GrandCompany', 'ItemSeries',
       'BaseParamModifier', 'Model{Main}', 'Model{Sub}', 'ClassJob{Use}',
       'Unnamed: 51', 'Damage{Phys}', 'Damage{Mag}', 'Delay<ms>',
       'Unnamed: 55', 'BlockRate', 'Block', 'Defense{Phys}', 'Defense{Mag}',
       'BaseParam[0]', 'BaseParamValue[0]', 'BaseParam[1]',
       'BaseParamValue[1]', 'BaseParam[2]', 'BaseParamValue[2]',
       'BaseParam[3]', 'BaseParamValue[3]', 'BaseParam[4]',
       'BaseParamValue[4]', 'BaseParam[5]', 'BaseParamValue[5]',
       'ItemSpecialBonus', 'ItemSpecialBonus{Param}', 'BaseParam{Special}[0]',
       'BaseParamValue{Special}[0]', 'BaseParam{Special}[1]',
       'BaseParamValue{Special}[1]', 'BaseParam{Special}[2]',
       'BaseParamValue{Special}[2]', 'BaseParam{Special}[3]',
       'BaseParamValue{Special}[3]', 'BaseParam{Special}[4]',
       'BaseParamValue{Special}[4]', 'BaseParam{Special}[5]',
       'BaseParamValue{Special}[5]', 'MaterializeType', 'MateriaSlotCount',
       'IsAdvancedMeldingPermitted', 'IsPvP', 'SubStatCategory',
       'IsGlamourous'],
      dtype='object')

In [35]:
df.head()

,#,Singular,Adjective,Plural,PossessivePronoun,StartsWithVowel,Unnamed: 6,Pronoun,Article,Description,...,BaseParam{Special}[4],BaseParamValue{Special}[4],BaseParam{Special}[5],BaseParamValue{Special}[5],MaterializeType,MateriaSlotCount,IsAdvancedMeldingPermitted,IsPvP,SubStatCategory,IsGlamourous
0,0,NaN,0,NaN,0,0,1,0,0,NaN,...,0,0,0,0,0,0,False,False,0,False
1,1,gil,0,gil,0,0,1,0,0,Standard Eorzean currency.,...,0,0,0,0,0,0,False,False,0,False
2,2,fire shard,0,fire shards,0,0,1,0,0,A tiny crystalline manifestation of aetheric f...,...,0,0,0,0,0,0,False,False,0,False
3,3,ice shard,0,ice shards,0,1,1,0,0,A tiny crystalline manifestation of aetheric i...,...,0,0,0,0,0,0,False,False,0,False
4,4,wind shard,0,wind shards,0,0,1,0,0,A tiny crystalline manifestation of aetheric w...,...,0,0,0,0,0,0,False,False,0,False

In [38]:
df["GrandCompany"].value_counts()

0    43854
3      183
2      182
1      182
Name: GrandCompany, dtype: int64

In [ ]:
#0 none 1 mael 2 adders 3 flames
#"\#", "name", 'StackSize', 'IsUnique', 'IsUntradable'

In [44]:
df[(df["GrandCompany"] == 1) & (df["IsUntradable"]!=True)]#["\#", "name", 'StackSize', 'IsUnique', 'IsUntradable']

Empty DataFrame
Columns: [#, Singular, Adjective, Plural, PossessivePronoun, StartsWithVowel, Unnamed: 6, Pronoun, Article, Description, Name, Icon, Level{Item}, Rarity, FilterGroup, AdditionalData, ItemUICategory, ItemSearchCategory, EquipSlotCategory, ItemSortCategory, Unnamed: 20, StackSize, IsUnique, IsUntradable, IsIndisposable, Lot, Price{Mid}, Price{Low}, CanBeHq, DyeCount, IsCrestWorthy, ItemAction, CastTime<s>, Cooldown<s>, ClassJob{Repair}, Item{Repair}, Item{Glamour}, Desynth, IsCollectable, AlwaysCollectable, AetherialReduce, Level{Equip}, RequiredPvpRank, EquipRestriction, ClassJobCategory, GrandCompany, ItemSeries, BaseParamModifier, Model{Main}, Model{Sub}, ClassJob{Use}, Unnamed: 51, Damage{Phys}, Damage{Mag}, Delay<ms>, Unnamed: 55, BlockRate, Block, Defense{Phys}, Defense{Mag}, BaseParam[0], BaseParamValue[0], BaseParam[1], BaseParamValue[1], BaseParam[2], BaseParamValue[2], BaseParam[3], BaseParamValue[3], BaseParam[4], BaseParamValue[4], BaseParam[5], BaseParamValue[5], ItemSpecialBonus, ItemSpecialBonus{Param}, BaseParam{Special}[0], BaseParamValue{Special}[0], BaseParam{Special}[1], BaseParamValue{Special}[1], BaseParam{Special}[2], BaseParamValue{Special}[2], BaseParam{Special}[3], BaseParamValue{Special}[3], BaseParam{Special}[4], BaseParamValue{Special}[4], BaseParam{Special}[5], BaseParamValue{Special}[5], MaterializeType, MateriaSlotCount, IsAdvancedMeldingPermitted, IsPvP, SubStatCategory, IsGlamourous]
Index: []

[0 rows x 92 columns]

In [51]:
df[df["Name"]=="Glass Fiber"]

,#,Singular,Adjective,Plural,PossessivePronoun,StartsWithVowel,Unnamed: 6,Pronoun,Article,Description,...,BaseParam{Special}[4],BaseParamValue{Special}[4],BaseParam{Special}[5],BaseParamValue{Special}[5],MaterializeType,MateriaSlotCount,IsAdvancedMeldingPermitted,IsPvP,SubStatCategory,IsGlamourous
15649,15649,loop of glass fiber,0,loops of glass fiber,0,0,1,0,0,Thinly spun glass remarkably resistant to high...,...,0,0,0,0,0,0,False,False,0,False

In [116]:
gcs = pd.read_csv("GCScripShopItem.csv", skiprows=[0,2,3])

In [117]:
gcs.head()

     #  Item  Required{GrandCompanyRank}  Cost{GCSeals}  SortKey
0  1.0  5594                           1             12       50
1  1.1  5595                           1             34       50
2  1.2  5596                           1             70       50
3  1.3  4564                           1            120       50
4  1.4  4566                           1            290       50

In [118]:
def maplink(df1,df2,keys):
    for key in keys:
        df1[key] = gcs["Item"].map(df.set_index("#")[key])

In [119]:
maplink(gcs,df, ["Name", 'StackSize', 'IsUnique', 'IsUntradable'])

In [120]:
gcs.columns[2]

'Required{GrandCompanyRank}'

In [121]:
gcs=gcs.rename(columns={gcs.columns[2]:"RequiredGCRank","Cost{GCSeals}":"GCSealsCost"})

In [122]:
gcs

,#,Item,RequiredGCRank,GCSealsCost,SortKey,Name,StackSize,IsUnique,IsUntradable
0,1.00,5594,1,12,50,Grade 1 Dark Matter,999,False,False
1,1.10,5595,1,34,50,Grade 2 Dark Matter,999,False,False
2,1.20,5596,1,70,50,Grade 3 Dark Matter,999,False,False
3,1.30,4564,1,120,50,Antidote,999,False,False
4,1.40,4566,1,290,50,Echo Drops,999,False,False
...,...,...,...,...,...,...,...,...,...
906,36.37,16933,9,4000,10,Pneumite,999,False,True
907,36.38,9356,9,2300,15,Quick-hardening Sealant,999,False,False
908,36.39,15649,9,7000,15,Glass Fiber,999,False,False
909,36.40,9357,11,2500,60,Xelphatol Spring Water,999,False,False
910,36.41,0,0,0,0,NaN,1,False,False

In [132]:
gcs["IsTradeable"] = gcs["IsUntradable"] ^ True

In [133]:
gcs[["Item","Name","RequiredGCRank","GCSealsCost","StackSize","IsUnique","IsTradeable"]].dropna()

,Item,Name,RequiredGCRank,GCSealsCost,StackSize,IsUnique,IsTradeable
0,5594,Grade 1 Dark Matter,1,12,999,False,True
1,5595,Grade 2 Dark Matter,1,34,999,False,True
2,5596,Grade 3 Dark Matter,1,70,999,False,True
3,4564,Antidote,1,120,999,False,True
4,4566,Echo Drops,1,290,999,False,True
...,...,...,...,...,...,...,...
905,10119,Duck Bones,9,600,999,False,False
906,16933,Pneumite,9,4000,999,False,False
907,9356,Quick-hardening Sealant,9,2300,999,False,True
908,15649,Glass Fiber,9,7000,999,False,True
909,9357,Xelphatol Spring Water,11,2500,999,False,True

In [130]:
gcs[gcs.isna().any(axis=1)]

,#,Item,RequiredGCRank,GCSealsCost,SortKey,Name,StackSize,IsUnique,IsUntradable
15,1.15,0,0,0,0,NaN,1,False,False
37,2.21,0,0,0,0,NaN,1,False,False
65,3.27,0,0,0,0,NaN,1,False,False
86,4.20,0,0,0,0,NaN,1,False,False
87,4.21,0,0,0,0,NaN,1,False,False
88,4.22,0,0,0,0,NaN,1,False,False
89,4.23,0,0,0,0,NaN,1,False,False
90,4.24,0,0,0,0,NaN,1,False,False
91,4.25,0,0,0,0,NaN,1,False,False
92,4.26,0,0,0,0,NaN,1,False,False
131,5.38,0,0,0,0,NaN,1,False,False
162,6.30,0,0,0,0,NaN,1,False,False
202,7.39,0,0,0,0,NaN,1,False,False
242,8.39,0,0,0,0,NaN,1,False,False
255,9.12,0,0,0,0,NaN,1,False,False
271,10.15,0,0,0,0,NaN,1,False,False
293,11.21,0,0,0,0,NaN,1,False,False
321,12.27,0,0,0,0,NaN,1,False,False
342,13.20,0,0,0,0,NaN,1,False,False
343,13.21,0,0,0,0,NaN,1,False,False
344,13.22,0,0,0,0,NaN,1,False,False
345,13.23,0,0,0,0,NaN,1,False,False
346,13.24,0,0,0,0,NaN,1,False,False
347,13.25,0,0,0,0,NaN,1,False,False
348,13.26,0,0,0,0,NaN,1,False,False
386,14.37,0,0,0,0,NaN,1,False,False
418,15.31,0,0,0,0,NaN,1,False,False
458,16.39,0,0,0,0,NaN,1,False,False
498,17.39,0,0,0,0,NaN,1,False,False
511,18.12,0,0,0,0,NaN,1,False,False
527,19.15,0,0,0,0,NaN,1,False,False
549,20.21,0,0,0,0,NaN,1,False,False
578,21.28,0,0,0,0,NaN,1,False,False
599,22.20,0,0,0,0,NaN,1,False,False
600,22.21,0,0,0,0,NaN,1,False,False
601,22.22,0,0,0,0,NaN,1,False,False
602,22.23,0,0,0,0,NaN,1,False,False
603,22.24,0,0,0,0,NaN,1,False,False
604,22.25,0,0,0,0,NaN,1,False,False
605,22.26,0,0,0,0,NaN,1,False,False
643,23.37,0,0,0,0,NaN,1,False,False
675,24.31,0,0,0,0,NaN,1,False,False
716,25.40,0,0,0,0,NaN,1,False,False
756,26.39,0,0,0,0,NaN,1,False,False
769,27.12,0,0,0,0,NaN,1,False,False
773,28.30,0,0,0,0,NaN,1,False,False
774,29.00,0,0,0,0,NaN,1,False,False
816,30.41,0,0,0,0,NaN,1,False,False
820,31.30,0,0,0,0,NaN,1,False,False
821,32.00,0,0,0,0,NaN,1,False,False
863,33.41,0,0,0,0,NaN,1,False,False
867,34.30,0,0,0,0,NaN,1,False,False
868,35.00,0,0,0,0,NaN,1,False,False
910,36.41,0,0,0,0,NaN,1,False,False

In [74]:
# gcs["Name"] = gcs["Item"].map(df.set_index("#")["Name"])

In [75]:
# gcs["IsUntradable"] = gcs["Item"].map(df.set_index("#")["IsUntradable"])

In [77]:
# gcs[gcs["IsUntradable"]==False]

,#,Item,Required{GrandCompanyRank},Cost{GCSeals},SortKey,Name,IsUntradable
0,1.00,5594,1,12,50,Grade 1 Dark Matter,False
1,1.10,5595,1,34,50,Grade 2 Dark Matter,False
2,1.20,5596,1,70,50,Grade 3 Dark Matter,False
3,1.30,4564,1,120,50,Antidote,False
4,1.40,4566,1,290,50,Echo Drops,False
...,...,...,...,...,...,...,...
897,36.28,9372,9,250,20,Roasted Coffee Beans,False
907,36.38,9356,9,2300,15,Quick-hardening Sealant,False
908,36.39,15649,9,7000,15,Glass Fiber,False
909,36.40,9357,11,2500,60,Xelphatol Spring Water,False
910,36.41,0,0,0,0,NaN,False

In [65]:
# df[df["#"] in list(gcs["Item"])]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [151]:
import pandas as pd

item_df = pd.read_csv("Item.csv",skiprows=[0,2])
gc_item_df = pd.read_csv("GCScripShopItem.csv", skiprows=[0,2,3])

def maplink(df1,df2,keys):
    for key in keys:
        df1[key] = gcs["Item"].map(df.set_index("#")[key])

maplink(gc_item_df,item_df, ["Name", 'StackSize', 'IsUnique', 'IsUntradable'])

gc_item_df=gc_item_df.rename(columns={gc_item_df.columns[2]:"RequiredGCRank","Cost{GCSeals}":"GCSealsCost"})

gc_item_df["IsTradeable"] = gc_item_df["IsUntradable"] ^ True 
gc_item_df = gc_item_df[["Item","Name","RequiredGCRank","GCSealsCost","StackSize","IsUnique","IsTradeable"]].dropna()
gc_item_df = gc_item_df.drop_duplicates()
gc_item_df=gc_item_df.set_index("Item")
gc_item_df.to_csv("gc_items.csv")
gc_item_df.to_json("gc_items.json", orient='index')

In [149]:
gc_item_df["Item"].value_counts()

5594     3
7526     3
21319    3
21320    3
22498    3
        ..
4436     1
3813     1
3811     1
3812     1
10546    1
Name: Item, Length: 621, dtype: int64

In [150]:
gc_item_df[gc_item_df["Item"]==5594]

,Item,Name,RequiredGCRank,GCSealsCost,StackSize,IsUnique,IsTradeable
0,5594,Grade 1 Dark Matter,1,12,999,False,True
256,5594,Grade 1 Dark Matter,1,12,999,False,True
512,5594,Grade 1 Dark Matter,1,12,999,False,True

In [152]:
from univ_tools import univ_client

# from univ_tools import univ_client
from xivjson import gc_ranks, servers_lookup, reverse_servers_lookup, gc_items
def get_univ_client():
    return univ_client()
univ_client = get_univ_client()

In [153]:
def cache_tradeables():
    import pandas as pd
    # df = pd.read_json(gc_items)
    # return df[df["IsTradeable"]]
    df = pd.DataFrame.from_dict(gc_items, orient='index')
    return df[df["IsTradeable"]]
tradeable_gc_items = cache_tradeables()

In [154]:
params = {
        'listings': 10,
        'entries': 30,
        'statsWithin': 1,
        # 'entriesWithin': 5*24*60*60*1000
        }
l = "".join([x+", " for x in tradeable_gc_items.index.to_list()])[:-2]

In [156]:
out = univ_client.raw_price_query(l, region="Faerie", params=params)

In [158]:
out.keys()

dict_keys(['itemIDs', 'items', 'worldID', 'unresolvedItems', 'worldName'])

In [160]:
out["unresolvedItems"] in out["itemIDs"] #ventures are tradeable? lmaooo

False

In [168]:
for x in out["items"][str(out["itemIDs"][0])].keys():
    print(x)

itemID
worldID
lastUploadTime
listings
recentHistory
currentAveragePrice
currentAveragePriceNQ
currentAveragePriceHQ
regularSaleVelocity
nqSaleVelocity
hqSaleVelocity
averagePrice
averagePriceNQ
averagePriceHQ
minPrice
minPriceNQ
minPriceHQ
maxPrice
maxPriceNQ
maxPriceHQ
stackSizeHistogram
stackSizeHistogramNQ
stackSizeHistogramHQ
worldName
listingsCount
recentHistoryCount
unitsForSale
unitsSold

In [167]:
out["items"][str(out["itemIDs"][0])]

{'itemID': 5594,
 'worldID': 54,
 'lastUploadTime': 1726339738467,
 'listings': [{'lastReviewTime': 1726339738,
   'pricePerUnit': 1,
   'quantity': 13,
   'stainID': 0,
   'creatorName': '',
   'creatorID': None,
   'hq': False,
   'isCrafted': False,
   'listingID': '3799912908330807',
   'materia': [],
   'onMannequin': False,
   'retainerCity': 4,
   'retainerID': '33777097242916980',
   'retainerName': 'Usagiska',
   'sellerID': None,
   'total': 13,
   'tax': 0},
  {'lastReviewTime': 1726339738,
   'pricePerUnit': 3,
   'quantity': 13,
   'stainID': 0,
   'creatorName': '',
   'creatorID': None,
   'hq': False,
   'isCrafted': False,
   'listingID': '3799912591247143',
   'materia': [],
   'onMannequin': False,
   'retainerCity': 3,
   'retainerID': '33777097240879716',
   'retainerName': 'Pototo-tato',
   'sellerID': None,
   'total': 39,
   'tax': 1},
  {'lastReviewTime': 1726339738,
   'pricePerUnit': 3,
   'quantity': 33,
   'stainID': 0,
   'creatorName': '',
   'creatorID': None,
   'hq': False,
   'isCrafted': False,
   'listingID': '3799912890670993',
   'materia': [],
   'onMannequin': False,
   'retainerCity': 1,
   'retainerID': '33777097242896148',
   'retainerName': 'Chahlie',
   'sellerID': None,
   'total': 99,
   'tax': 4},
  {'lastReviewTime': 1726339738,
   'pricePerUnit': 10,
   'quantity': 13,
   'stainID': 0,
   'creatorName': '',
   'creatorID': None,
   'hq': False,
   'isCrafted': False,
   'listingID': '3799912455767598',
   'materia': [],
   'onMannequin': False,
   'retainerCity': 3,
   'retainerID': '33777097238954411',
   'retainerName': 'Arivelle',
   'sellerID': None,
   'total': 130,
   'tax': 6},
  {'lastReviewTime': 1726339738,
   'pricePerUnit': 21,
   'quantity': 45,
   'stainID': 0,
   'creatorName': '',
   'creatorID': None,
   'hq': False,
   'isCrafted': False,
   'listingID': '3799912856151626',
   'materia': [],
   'onMannequin': False,
   'retainerCity': 4,
   'retainerID': '33777097242399135',
   'retainerName': 'Jakefox',
   'sellerID': None,
   'total': 945,
   'tax': 47},
  {'lastReviewTime': 1726339738,
   'pricePerUnit': 21,
   'quantity': 90,
   'stainID': 0,
   'creatorName': '',
   'creatorID': None,
   'hq': False,
   'isCrafted': False,
   'listingID': '3799912913647523',
   'materia': [],
   'onMannequin': False,
   'retainerCity': 3,
   'retainerID': '33777097242496737',
   'retainerName': 'Tygu',
   'sellerID': None,
   'total': 1890,
   'tax': 94},
  {'lastReviewTime': 1726339738,
   'pricePerUnit': 21,
   'quantity': 99,
   'stainID': 0,
   'creatorName': '',
   'creatorID': None,
   'hq': False,
   'isCrafted': False,
   'listingID': '3799912950917365',
   'materia': [],
   'onMannequin': False,
   'retainerCity': 4,
   'retainerID': '33777097242399135',
   'retainerName': 'Jakefox',
   'sellerID': None,
   'total': 2079,
   'tax': 103},
  {'lastReviewTime': 1726339738,
   'pricePerUnit': 40,
   'quantity': 20,
   'stainID': 0,
   'creatorName': '',
   'creatorID': None,
   'hq': False,
   'isCrafted': False,
   'listingID': '3799912947269418',
   'materia': [],
   'onMannequin': False,
   'retainerCity': 1,
   'retainerID': '33777097242640082',
   'retainerName': 'Luna-nene',
   'sellerID': None,
   'total': 800,
   'tax': 40},
  {'lastReviewTime': 1726339738,
   'pricePerUnit': 50,
   'quantity': 3,
   'stainID': 0,
   'creatorName': '',
   'creatorID': None,
   'hq': False,
   'isCrafted': False,
   'listingID': '3799912908438304',
   'materia': [],
   'onMannequin': False,
   'retainerCity': 1,
   'retainerID': '33777097242820503',
   'retainerName': 'Weweqae',
   'sellerID': None,
   'total': 150,
   'tax': 7},
  {'lastReviewTime': 1726339738,
   'pricePerUnit': 55,
   'quantity': 3,
   'stainID': 0,
   'creatorName': '',
   'creatorID': None,
   'hq': False,
   'isCrafted': False,
   'listingID': '3799912912179647',
   'materia': [],
   'onMannequin': False,
   'retainerCity': 3,
   'retainerID': '33777097242881510',
   'retainerName': 'Aardvarkseller',
   'sellerID': None,
   'total': 165,
   'tax': 8}],
 'recentHistory': [{'hq': False,
   'pricePerUnit': 45,
   'quantity': 3,
   'timestamp': 1726043149,
   'onMannequin': False,
   'buyerName': 'Dr Frost',
   'total': 135},
  {'hq': False,
   'pricePerUnit': 20,
   'quantity': 10,
   'timestamp': 1726026831,
   'onMannequin': False,
   'buyerName': 'Sarin Megistus',
   'total': 200},
  {'hq': False,
   'pricePerUnit': 20,
   'quantity': 53,
   'timestamp': 1725926239,
   'onMannequin': False,
   'buyerName': 'Sicard Spence',
   'total': 1060},
  {'hq': False,
   'pricePerUnit': 1,
   'quantity': 10,
   'timestamp': 1725913419,
   'onMannequin': False,
   'buyerName': 'Noel Lockhart',
   'total': 10},
  {'hq': False,
   'pricePerUnit': 1,
   'quantity': 13,
   'timestamp': 1725878059,
   'onMannequin': False,
   'buyerName': 'Leeva Lee',
   'total': 13},
  {'hq': False,
   'pricePerUnit': 20,
   'quantity': 23,
   'timestamp': 1725552512,
   'onMannequin': False,
   'buyerName': 'Jay Hoshi',
   'total': 460},
  {'hq': False,
   'pricePerUnit': 61,
   'quantity': 99,
   'timestamp': 1725521704,
   'onMannequin': False,
   'buyerName': 'Doomy Dino',
   'total': 6039},
  {'hq': False,
   'pricePerUnit': 1,
   'quantity': 13,
   'timestamp': 1725463267,
   'onMannequin': False,
   'buyerName': 'Izzy Lefonte',
   'total': 13},
  {'hq': False,
   'pricePerUnit': 49,
   'quantity': 3,
   'timestamp': 1724691134,
   'onMannequin': False,
   'buyerName': 'Peach Milk',
   'total': 147},
  {'hq': False,
   'pricePerUnit': 50,
   'quantity': 13,
   'timestamp': 1724621184,
   'onMannequin': False,
   'buyerName': 'Primo Lion',
   'total': 650},
  {'hq': False,
   'pricePerUnit': 31,
   'quantity': 10,
   'timestamp': 1724621155,
   'onMannequin': False,
   'buyerName': 'Primo Lion',
   'total': 310},
  {'hq': False,
   'pricePerUnit': 10,
   'quantity': 63,
   'timestamp': 1724366618,
   'onMannequin': False,
   'buyerName': 'Mistress Seika',
   'total': 630},
  {'hq': False,
   'pricePerUnit': 20,
   'quantity': 3,
   'timestamp': 1724141388,
   'onMannequin': False,
   'buyerName': 'Syrenead Yapa',
   'total': 60},
  {'hq': False,
   'pricePerUnit': 15,
   'quantity': 23,
   'timestamp': 1724141383,
   'onMannequin': False,
   'buyerName': 'Syrenead Yapa',
   'total': 345},
  {'hq': False,
   'pricePerUnit': 11,
   'quantity': 10,
   'timestamp': 1724141380,
   'onMannequin': False,
   'buyerName': 'Syrenead Yapa',
   'total': 110},
  {'hq': False,
   'pricePerUnit': 11,
   'quantity': 10,
   'timestamp': 1724141377,
   'onMannequin': False,
   'buyerName': 'Syrenead Yapa',
   'total': 110},
  {'hq': False,
   'pricePerUnit': 9,
   'quantity': 3,
   'timestamp': 1724141375,
   'onMannequin': False,
   'buyerName': 'Syrenead Yapa',
   'total': 27},
  {'hq': False,
   'pricePerUnit': 8,
   'quantity': 3,
   'timestamp': 1724141373,
   'onMannequin': False,
   'buyerName': 'Syrenead Yapa',
   'total': 24},
  {'hq': False,
   'pricePerUnit': 8,
   'quantity': 13,
   'timestamp': 1724141372,
   'onMannequin': False,
   'buyerName': 'Syrenead Yapa',
   'total': 104},
  {'hq': False,
   'pricePerUnit': 1,
   'quantity': 13,
   'timestamp': 1724141370,
   'onMannequin': False,
   'buyerName': 'Syrenead Yapa',
   'total': 13},
  {'hq': False,
   'pricePerUnit': 1,
   'quantity': 3,
   'timestamp': 1724107393,
   'onMannequin': False,
   'buyerName': 'Syrenead Yapa',
   'total': 3},
  {'hq': False,
   'pricePerUnit': 1,
   'quantity': 20,
   'timestamp': 1724107390,
   'onMannequin': False,
   'buyerName': 'Syrenead Yapa',
   'total': 20},
  {'hq': False,
   'pricePerUnit': 100,
   'quantity': 99,
   'timestamp': 1723866705,
   'onMannequin': False,
   'buyerName': 'Fuji Yokimoni',
   'total': 9900},
  {'hq': False,
   'pricePerUnit': 1,
   'quantity': 13,
   'timestamp': 1723823253,
   'onMannequin': False,
   'buyerName': 'Alea Akras',
   'total': 13},
  {'hq': False,
   'pricePerUnit': 10,
   'quantity': 10,
   'timestamp': 1722873955,
   'onMannequin': False,
   'buyerName': 'Lune Violette',
   'total': 100},
  {'hq': False,
   'pricePerUnit': 20,
   'quantity': 3,
   'timestamp': 1722800263,
   'onMannequin': False,
   'buyerName': "S'paroh Pond",
   'total': 60},
  {'hq': False,
   'pricePerUnit': 11,
   'quantity': 13,
   'timestamp': 1722800261,
   'onMannequin': False,
   'buyerName': "S'paroh Pond",
   'total': 143},
  {'hq': False,
   'pricePerUnit': 11,
   'quantity': 13,
   'timestamp': 1722800260,
   'onMannequin': False,
   'buyerName': "S'paroh Pond",
   'total': 143},
  {'hq': False,
   'pricePerUnit': 5,
   'quantity': 4,
   'timestamp': 1722800259,
   'onMannequin': False,
   'buyerName': "S'paroh Pond",
   'total': 20},
  {'hq': False,
   'pricePerUnit': 1,
   'quantity': 3,
   'timestamp': 1722800257,
   'onMannequin': False,
   'buyerName': "S'paroh Pond",
   'total': 3}],
 'currentAveragePrice': 22.5,
 'currentAveragePriceNQ': 22.5,
 'currentAveragePriceHQ': 0,
 'regularSaleVelocity': 0,
 'nqSaleVelocity': 0,
 'hqSaleVelocity': 0,
 'averagePrice': 18.433332,
 'averagePriceNQ': 18.433332,
 'averagePriceHQ': 0,
 'minPrice': 1,
 'minPriceNQ': 1,
 'minPriceHQ': 0,
 'maxPrice': 55,
 'maxPriceNQ': 55,
 'maxPriceHQ': 0,
 'stackSizeHistogram': {'3': 2,
  '13': 3,
  '20': 1,
  '33': 1,
  '45': 1,
  '90': 1,
  '99': 1},
 'stackSizeHistogramNQ': {'3': 2,
  '13': 3,
  '20': 1,
  '33': 1,
  '45': 1,
  '90': 1,
  '99': 1},
 'stackSizeHistogramHQ': {},
 'worldName': 'Faerie',
 'listingsCount': 10,
 'recentHistoryCount': 30,
 'unitsForSale': 332,
 'unitsSold': 572}

In [175]:
_=[print(x) for x in out["items"][str(out["itemIDs"][0])]["listings"][0].items()]

('lastReviewTime', 1726339738)
('pricePerUnit', 1)
('quantity', 13)
('stainID', 0)
('creatorName', '')
('creatorID', None)
('hq', False)
('isCrafted', False)
('listingID', '3799912908330807')
('materia', [])
('onMannequin', False)
('retainerCity', 4)
('retainerID', '33777097242916980')
('retainerName', 'Usagiska')
('sellerID', None)
('total', 13)
('tax', 0)

In [188]:
def process_listings(listings, window=7*24*60*60):
    lowest_price = None
    listings_updated = 0
    unique_retainers = {}
    t = int(time.time())
    for x in listings:
        if x["onMannequin"]:
            continue
        if t-x["lastReviewTime"] > window:
            continue
        if lowest_price is None or x["pricePerUnit"] < lowest_price:
            lowest_price = x["pricePerUnit"]
        listings_updated += 1
        unique_retainers[x["retainerID"]]=True

    return lowest_price, listings_updated, len(unique_retainers.keys())

process_listings(out["items"][str(out["itemIDs"][0])]["listings"])

(1, 10, 9)

In [174]:
_=[print(x) for x in out["items"][str(out["itemIDs"][0])]["recentHistory"][0].items()]

('hq', False)
('pricePerUnit', 45)
('quantity', 3)
('timestamp', 1726043149)
('onMannequin', False)
('buyerName', 'Dr Frost')
('total', 135)

In [177]:
import time
int(time.time())-1726043149

615297

In [184]:
def process_sales(sales, window=7*24*60*60, max_count=None):
    #"Avg price per", "Listings sold", "Items Sold", "Unique Buyers",
    pass
    #filter mannequins, launderers
    t = time.time()
    listings_sold = 0
    items_sold = 0
    avg_price = [] #per listing, not per item in stack
    unique_buyers = {}
    for x in sales:
        if x["onMannequin"]:
            continue
        if int(t)-x["timestamp"] > window:
            # print(int(t)-x["timestamp"],window)
            continue
        unique_buyers[x['buyerName']] = True
        avg_price += x['pricePerUnit']
        items_sold += x["quantity"]
        listings_sold += 1

    avg = sum(avg_price)/len(avg_price) if len(avg_price)!= 0 else -1 

    return listings_sold, items_sold, avg, len(unique_buyers.keys())

process_sales(out["items"][str(out["itemIDs"][0])]["recentHistory"])

TypeError: string indices must be integers